@url = http://localhost:3000

POST {{url}}/users/register
Content-Type: application/json

{
    "email":"kiril1@gamil.ocm",
    "password":"12345678K"
}

###

POST {{url}}/users/login
Content-Type: application/json

{
    "email":"kiril@gamil.ocm",
    "password":"0123456789K"
}

###

POST {{url}}/users/reset-password
Content-Type: application/json

{
    "email":"kiril@gamil.ocm",
    "newPassword":"0123456789K"
}

###

GET {{url}}/todos/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY5MzQwMTczMCwiZXhwIjoxNjkzNDA1MzMwfQ.rgO1DjQPzMUlmbLB3tBzxlJqcWMuyewAprJ8NNIGoVQ

###

POST {{url}}/todos/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY5MzQwMTczMCwiZXhwIjoxNjkzNDA1MzMwfQ.rgO1DjQPzMUlmbLB3tBzxlJqcWMuyewAprJ8NNIGoVQ


{
    "todo":"123"
}

###

PUT {{url}}/todos/update/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY5MzQwMTczMCwiZXhwIjoxNjkzNDA1MzMwfQ.rgO1DjQPzMUlmbLB3tBzxlJqcWMuyewAprJ8NNIGoVQ

{
    "todo":"1234",
    "completed":true
}

###

DELETE {{url}}/todos/delete/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY5MzQwMTczMCwiZXhwIjoxNjkzNDA1MzMwfQ.rgO1DjQPzMUlmbLB3tBzxlJqcWMuyewAprJ8NNIGoVQ