@url = http://localhost:3000

POST {{url}}/users/register
Content-Type: application/json

{
    "email":"bhhjj",
    "password":"1234"
}

###

POST {{url}}/users/login
Content-Type: application/json

{
    "email":"bhhjj",
    "password":"1234"
}

###

POST {{url}}/todos/create
Content-Type: application/json

{
    "todo":"123"
}

###

GET {{url}}/todos/list
Content-Type: application/json

###

PUT {{url}}/todos/update/1
Content-Type: application/json

{
    "todo":"1234",
    "completed":false
}

###

DELETE {{url}}/todos/delete/1
Content-Type: application/json