@url = http://localhost:3000

POST {{url}}/users/register
Content-Type: application/json

{
    "email":"superAcc",
    "password":"277353"
}

###

POST {{url}}/users/login
Content-Type: application/json

{
    "email":"superAcc",
    "password":"277353"
}

###

POST {{url}}/todos/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY5MzIxODg2MywiZXhwIjoxNjkzMjIyNDYzfQ.MDxkzsPyONliYggO-H2Q5ACsDBPz7iMjDFMo_Vm7VhY


{
    "todo":"123"
}

###

GET {{url}}/todos/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY5MzIxODg2MywiZXhwIjoxNjkzMjIyNDYzfQ.MDxkzsPyONliYggO-H2Q5ACsDBPz7iMjDFMo_Vm7VhY

###

PUT {{url}}/todos/update/1
Content-Type: application/json

{
    "todo":"1234",
    "completed":false
}

###

DELETE {{url}}/todos/delete/1
Content-Type: application/json