version: '3.8'

services:
  app:
    container_name: node_app
    build: .
    image: node_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=db
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_HOST=db
    volumes:
      - ./:/home/node/app
      - ./App/models:/home/node/app/models
    depends_on:
      - db
    command: npm run dev
    restart: always
  db:
    container_name: node_db
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - node_bd_data:/Library/PostgreSQL/15/data

volumes:
  node_bd_data: {}